{
  "services": {
    "zpush": {
      "restart": "unless-stopped",
      "environment": {
        "TZ": "Europe/Vienna",
        "ZPUSH_DEFAULT_LOGIN_DOMAIN": "kniff.at",
        "IMAP_IDLE_ENABLED": "true"
      },
      "volumes": [
        "zpush-data:/var/lib/z-push",
        "zpush-logs:/var/log/z-push"
      ],
      "build": ".",
      "expose": [
        "8080"
      ]
    }
  },
  "volumes": {
    "zpush-data": {
      "external": true,
      "name": "b480ccskccs4g4wks8cc8sw8_zpush-data"
    },
    "zpush-logs": {
      "external": true,
      "name": "b480ccskccs4g4wks8cc8sw8_zpush-logs"
    }
  }
}
