worker_processes auto;
pid /run/nginx/nginx.pid;
error_log /dev/stderr warn;
events { worker_connections 1024; }
http {
    access_log /dev/stdout;
    include /etc/nginx/mime.types;
    server_tokens off;
    server {
        listen 8080;
        root /usr/share/z-push;
        client_max_body_size 20m;
        location = /health {
            access_log off;
            include /opt/z-push/fastcgi.conf;
            fastcgi_param SCRIPT_FILENAME /opt/z-push/health.php;
        }
        location = / { return 200 "Z-Push ActiveSync\n"; }
        location = /Microsoft-Server-ActiveSync {
            include /opt/z-push/fastcgi.conf;
            fastcgi_param SCRIPT_FILENAME /usr/share/z-push/index.php;
        }
        location ~* ^/autodiscover/autodiscover\.xml$ {
            include /opt/z-push/fastcgi.conf;
            fastcgi_param SCRIPT_FILENAME /usr/share/z-push/autodiscover/autodiscover.php;
        }
        location / { return 404; }
    }
}
